apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: petclinic-secrets
  namespace: petclinic
spec:
  provider: aws
  parameters:
    region: {{ .Values.csi.region }}
    objects: |
      - objectName: {{ .Values.csi.secretName | quote }}
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: dbuser
          - path: password
            objectAlias: dbpass
  secretObjects:
    - secretName: petclinic-k8s-secret
      type: Opaque
      data:
        - objectName: dbuser
          key: db-username
        - objectName: dbpass
          key: db-password
